//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sirius.CustomControls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sirius.CustomControls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap icon_16_accept {
            get {
                object obj = ResourceManager.GetObject("icon_16_accept", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_add {
            get {
                object obj = ResourceManager.GetObject("icon_16_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_arrow_refresh {
            get {
                object obj = ResourceManager.GetObject("icon_16_arrow_refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_binoculars {
            get {
                object obj = ResourceManager.GetObject("icon_16_binoculars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_book {
            get {
                object obj = ResourceManager.GetObject("icon_16_book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_calendar {
            get {
                object obj = ResourceManager.GetObject("icon_16_calendar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_cancel {
            get {
                object obj = ResourceManager.GetObject("icon_16_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_chart_bar {
            get {
                object obj = ResourceManager.GetObject("icon_16_chart_bar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_chart_curve {
            get {
                object obj = ResourceManager.GetObject("icon_16_chart_curve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_chart_organisation {
            get {
                object obj = ResourceManager.GetObject("icon_16_chart_organisation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_clock {
            get {
                object obj = ResourceManager.GetObject("icon_16_clock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_cog {
            get {
                object obj = ResourceManager.GetObject("icon_16_cog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_cross {
            get {
                object obj = ResourceManager.GetObject("icon_16_cross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_date {
            get {
                object obj = ResourceManager.GetObject("icon_16_date", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_delete {
            get {
                object obj = ResourceManager.GetObject("icon_16_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_disk {
            get {
                object obj = ResourceManager.GetObject("icon_16_disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_door_in {
            get {
                object obj = ResourceManager.GetObject("icon_16_door_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_funnel {
            get {
                object obj = ResourceManager.GetObject("icon_16_funnel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_group {
            get {
                object obj = ResourceManager.GetObject("icon_16_group", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_help {
            get {
                object obj = ResourceManager.GetObject("icon_16_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_information {
            get {
                object obj = ResourceManager.GetObject("icon_16_information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_key {
            get {
                object obj = ResourceManager.GetObject("icon_16_key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_lightning {
            get {
                object obj = ResourceManager.GetObject("icon_16_lightning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_lock {
            get {
                object obj = ResourceManager.GetObject("icon_16_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_lock_open {
            get {
                object obj = ResourceManager.GetObject("icon_16_lock_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_page_edit {
            get {
                object obj = ResourceManager.GetObject("icon_16_page_edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_printer {
            get {
                object obj = ResourceManager.GetObject("icon_16_printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_table_go {
            get {
                object obj = ResourceManager.GetObject("icon_16_table_go", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_tick {
            get {
                object obj = ResourceManager.GetObject("icon_16_tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_user {
            get {
                object obj = ResourceManager.GetObject("icon_16_user", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_add_category {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_add_category", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_add_file {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_add_file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_arrow_return_left_blue {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_arrow_return_left_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_arrow_return_right_blue {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_arrow_return_right_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_back {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_book_report {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_book_report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_book_stack_reports {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_book_stack_reports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_breakpoint {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_breakpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_calendar_schedule {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_calendar_schedule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_choose_color {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_choose_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_color {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_command_link {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_command_link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_copy {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_delete {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_document_empty {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_document_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_double_left_arrow {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_double_left_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_double_right_arrow {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_double_right_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_edit_information {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_edit_information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_edit_redo {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_edit_redo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_edit_undo {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_edit_undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_envelope_closed {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_envelope_closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_envelope_open_large {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_envelope_open_large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_favorite_star {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_favorite_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_folder_close {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_folder_close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_folder_open {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_forward {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_get_permission {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_get_permission", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_go_left {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_go_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_go_right {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_go_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_go_to_next {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_go_to_next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_go_to_next_record {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_go_to_next_record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_go_to_previous {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_go_to_previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_go_to_previous_record {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_go_to_previous_record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_graph {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_graph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_help {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_history {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_legend {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_legend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_nav_back {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_nav_back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_nav_forward {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_nav_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_note {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_note", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_open_folder {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_open_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_options {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_options", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_org_chart {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_org_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_organizer {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_organizer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_pie_chart {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_pie_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_properties {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_protect_form {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_protect_form", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_refresh_arrow_blue {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_refresh_arrow_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_refresh_arrow_green {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_refresh_arrow_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_repeat {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_repeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_restart {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_restart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_save {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_save_all {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_save_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_show_rule_lines {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_show_rule_lines", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_sort_green {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_sort_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_up_folder {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_up_folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_warning {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_zoom {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_win_zoom_in {
            get {
                object obj = ResourceManager.GetObject("icon_16_win_zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_wrench {
            get {
                object obj = ResourceManager.GetObject("icon_16_wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap icon_16_zoom {
            get {
                object obj = ResourceManager.GetObject("icon_16_zoom", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap logo_radan {
            get {
                object obj = ResourceManager.GetObject("logo_radan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
