//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sirius.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaborator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collaborator()
        {
            this.CollaboratorLocations = new HashSet<CollaboratorLocation>();
        }
    
        public int Id { get; set; }
        public string NameFull { get; set; }
        public string NameFriendly { get; set; }
        public string NameShort3 { get; set; }
        public string NameShort2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollaboratorLocation> CollaboratorLocations { get; set; }
    }
}
