//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sirius.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollaboratorLocation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsDefault { get; set; }
        public int CollaboratorId { get; set; }
    
        public virtual Collaborator Collaborator { get; set; }
    }
}
