//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infonova.Data.Models.Infonova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.ArticlePackages = new HashSet<ArticlePackage>();
            this.PurchaseOrderProducts = new HashSet<PurchaseOrderProduct>();
            this.SaleOrderProducts = new HashSet<SaleOrderProduct>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string NameFull { get; set; }
        public string NameFromSupplier { get; set; }
        public string NameInvoice { get; set; }
        public bool IsCalibrated { get; set; }
        public double UnitWeightFactor { get; set; }
        public bool IsForbiddenUnitySale { get; set; }
        public bool IsForbiddenUnityPurchase { get; set; }
        public int ArticleSubGroupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticlePackage> ArticlePackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderProduct> PurchaseOrderProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderProduct> SaleOrderProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual ArticleSubGroup ArticleSubGroup { get; set; }
    }
}
