//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infonova.Data.Models.Infonova
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticlePackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArticlePackage()
        {
            this.SaleOrderProducts = new HashSet<SaleOrderProduct>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double Weight { get; set; }
        public decimal Cost { get; set; }
        public bool IsReusable { get; set; }
        public double UnitMultiplicationFactor { get; set; }
        public int SelectionPriority { get; set; }
        public bool IsRetired { get; set; }
        public int ArticleId { get; set; }
        public Nullable<int> CollaboratorId { get; set; }
    
        public virtual Article Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderProduct> SaleOrderProducts { get; set; }
        public virtual Collaborator Collaborator { get; set; }
    }
}
