//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infonova.Data.Models.Infonova
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollaboratorLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollaboratorLocation()
        {
            this.SaleAgentRouteCollaborators = new HashSet<SaleAgentRouteCollaborator>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public bool IsHeadquarters { get; set; }
        public bool IsGPSDetermined { get; set; }
        public Nullable<System.DateTime> DateGPSDetermined { get; set; }
        public double GPSLongitude { get; set; }
        public double GPSLatitude { get; set; }
        public int CountryId { get; set; }
        public int CollaboratorId { get; set; }
    
        public virtual Collaborator Collaborator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleAgentRouteCollaborator> SaleAgentRouteCollaborators { get; set; }
        public virtual Country Country { get; set; }
    }
}
