//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infonova.Data.Models.Infonova
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollaboratorArticle
    {
        public int Id { get; set; }
        public string NameFull { get; set; }
        public string NameFriendly { get; set; }
        public string NameInvoice { get; set; }
        public string Code { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CollaboratorId { get; set; }
        public int CollaboratorArticleGroupId { get; set; }
    
        public virtual CollaboratorArticleGroup CollaboratorArticleGroup { get; set; }
        public virtual Collaborator Collaborator { get; set; }
    }
}
