//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infonova.Data.Models.Infonova
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyLocation()
        {
            this.Warehouses = new HashSet<Warehouse>();
            this.EmployeeGroups = new HashSet<EmployeeGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsHeadquarters { get; set; }
        public string AddressDistrict { get; set; }
        public string AddressLocality { get; set; }
        public string AddressStreet { get; set; }
        public string AddressPostalCode { get; set; }
        public string PhoneNumbers { get; set; }
        public string FaxNumbers { get; set; }
        public string Emails { get; set; }
        public int CountryId { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Warehouse> Warehouses { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeGroup> EmployeeGroups { get; set; }
    }
}
