//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infonova.Data.Models.Infonova
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelInfonova : DbContext
    {
        public ModelInfonova()
            : base("name=ModelInfonova")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArticleCategory> ArticleCategories { get; set; }
        public virtual DbSet<ArticleGroup> ArticleGroups { get; set; }
        public virtual DbSet<ArticlePackage> ArticlePackages { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<ArticleSubGroup> ArticleSubGroups { get; set; }
        public virtual DbSet<CollaboratorArticleGroup> CollaboratorArticleGroups { get; set; }
        public virtual DbSet<CollaboratorArticle> CollaboratorArticles { get; set; }
        public virtual DbSet<CollaboratorLocation> CollaboratorLocations { get; set; }
        public virtual DbSet<Collaborator> Collaborators { get; set; }
        public virtual DbSet<CollaboratorUser> CollaboratorUsers { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyEmployeeEnrollment> CompanyEmployeeEnrollments { get; set; }
        public virtual DbSet<CompanyLocation> CompanyLocations { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<CurrencyExchangeRate> CurrencyExchangeRates { get; set; }
        public virtual DbSet<EmailMessage> EmailMessages { get; set; }
        public virtual DbSet<EmployeeGroupPermission> EmployeeGroupPermissions { get; set; }
        public virtual DbSet<EmployeeGroup> EmployeeGroups { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<PurchaseOrderProduct> PurchaseOrderProducts { get; set; }
        public virtual DbSet<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<SaleAgentRouteCollaborator> SaleAgentRouteCollaborators { get; set; }
        public virtual DbSet<SaleAgentRoute> SaleAgentRoutes { get; set; }
        public virtual DbSet<SaleOrderProduct> SaleOrderProducts { get; set; }
        public virtual DbSet<SaleOrder> SaleOrders { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<VAT> VATs { get; set; }
        public virtual DbSet<WarehouseContainer> WarehouseContainers { get; set; }
        public virtual DbSet<WarehouseRoom> WarehouseRooms { get; set; }
        public virtual DbSet<WarehouseRow> WarehouseRows { get; set; }
        public virtual DbSet<Warehouse> Warehouses { get; set; }
    }
}
