//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infonova.Data.Models.Infonova
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderProduct
    {
        public int Id { get; set; }
        public double Quantity { get; set; }
        public int ArticleId { get; set; }
        public int PurchaseOrderId { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
