//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infonova.Data.Models.Infonova
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleAgentRouteCollaborator
    {
        public int Id { get; set; }
        public int Position { get; set; }
        public int SaleAgentRouteId { get; set; }
        public int CollaboratorLocationId { get; set; }
    
        public virtual CollaboratorLocation CollaboratorLocation { get; set; }
        public virtual SaleAgentRoute SaleAgentRoute { get; set; }
    }
}
