//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infonova.Data.Models.Infonova
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleOrder()
        {
            this.SaleOrderProducts = new HashSet<SaleOrderProduct>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateSale { get; set; }
        public bool IsClosed { get; set; }
        public int CompanyId { get; set; }
        public int EmployeeId { get; set; }
        public int CollaboratorId { get; set; }
    
        public virtual Collaborator Collaborator { get; set; }
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleOrderProduct> SaleOrderProducts { get; set; }
    }
}
