//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infonova.Data.Models.Infonova
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrderProduct
    {
        public int Id { get; set; }
        public double QuantityUnity { get; set; }
        public double QuantityPackage { get; set; }
        public decimal PriceWithoutVAT { get; set; }
        public int ArticleId { get; set; }
        public Nullable<int> ArticlePackageId { get; set; }
        public int SaleOrderId { get; set; }
    
        public virtual ArticlePackage ArticlePackage { get; set; }
        public virtual Article Article { get; set; }
        public virtual SaleOrder SaleOrder { get; set; }
    }
}
