//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infonova.Data.Models.Infonova
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarehouseRow
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public bool IsMirrored { get; set; }
        public int WarehouseRoomId { get; set; }
    
        public virtual WarehouseRoom WarehouseRoom { get; set; }
    }
}
